---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: dotfiles
    - role: iterm2
    - role: macports
    - role: terraform
    - role: elliotweiser.osx-command-line-tools

